apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: auth-app-ui
  name: auth-app-ui
spec:
  type: NodePort
  ports:
    - name: "5000"
      port: 5000
      targetPort: 80
      nodePort: 30303
  selector:
    io.kompose.service: auth-app-ui
status:
  loadBalancer: {}
